"""empty message

Revision ID: 937542db0cc8
Revises: f1f2b381039b
Create Date: 2024-02-05 12:10:51.062720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937542db0cc8'
down_revision = 'f1f2b381039b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('username', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'password')
    op.drop_column('user_table', 'username')
    # ### end Alembic commands ###
